/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle.kotlin.app

import com.aliyun.oss.OSS as OSSClient
import com.aliyun.oss.OSSClientBuilder
import com.aliyun.oss.model.PutObjectRequest as OSSPutObjectRequest
import com.aliyun.oss.model.PutObjectResult as OSSPutObjectResult

import software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider
import software.amazon.awssdk.regions.Region
import software.amazon.awssdk.services.s3.S3Client
import software.amazon.awssdk.services.s3.model.PutObjectRequest as S3PutObjectRequest
import software.amazon.awssdk.services.s3.model.PutObjectResponse as S3PutObjectResponse

import java.io.File
import java.nio.file.Paths


class App {
    private val s3Client: S3Client
        get() {
            val c = ProfileCredentialsProvider.builder().profileName("profileName").build()
            return S3Client.builder().credentialsProvider(c).region(Region.CN_NORTH_1).build()
        }
    private val ossClient: OSSClient
        get() {
            return OSSClientBuilder().build("https://oss-cn-hangzhou.aliyuncs.com", "ak", "sk")
        }

    fun uploadToS3(filePath: String): S3PutObjectResponse {
        val req = S3PutObjectRequest.builder().key(filePath).bucket("examplebucket").build()
        return s3Client.putObject(req, Paths.get(filePath))
    }

    fun uploadToOss(filePath: String): OSSPutObjectResult {
        val req =
            OSSPutObjectRequest("examplebucket", filePath, File(filePath))
        return ossClient.putObject(req)
    }

}


fun main() {
    val app = App()
    val s3UploadRes = app.uploadToS3("/xxx.txt")
    println(s3UploadRes.toString())

    val ossUploadRes = app.uploadToOss("/xxx.txt")
    println(ossUploadRes.toString())
}
